### PR TITLE
Fix external use example in readme

### PR DESCRIPTION
**Pull request by jmerle**
This PR updates the "External use" example in the readme to fix two bugs:
1. The `RGBot` constructor requires a match info event emitter as second argument, which is currently omitted.
2. The `RGBot` constructor constructs a new `Movements` instance when it is executed, and [the `Movements` constructor uses `bot.registry`](https://github.com/PrismarineJS/mineflayer-pathfinder/blob/master/lib/movements.js#L19-L21). [`bot.registry` is not available until the `inject_allowed` event has been fired on the Mineflayer bot](https://github.com/PrismarineJS/mineflayer/blob/master/lib/loader.js#L108-L127), while in the current example `RGBot` is constructed before that happens.

### CODE REVIEW

**Review by vontell — APPROVED** [review]

**Comment by RG-nAmKcAz** [comment]
I have not approved this yet because we are in the process of 'probably' removing that second argument as a requirement and making the RGBot itself an `EventEmitter`.  

On the surface of it, this would mean that `rgbot.on(...)` would have a different meaning than `rgbot.mineflayer().on(...)`, where the former is for rg-match-info events and the latter would be for mineflayer specific events.  That said, we are still discussing internally and evaluating options as we hopefully would be able to make `rgbot.on(...)` work seamlessly for both cases while still removing that second argument.

**Comment by RG-nAmKcAz** [comment]
@jmerle Regarding the `inject_allowed` change.  I think this needs to be conditional.
When the `mineflayer.createBot(...)` call returns to us, it might be ready to use and it might not, which all depends on whether the server was ready to accept its connection while it was being created.
https://github.com/PrismarineJS/mineflayer/blob/master/lib/loader.js

It looks like the code should probably check so see if `next()` was called yet or not.
```javascript
if (bot.version)

**Comment by RG-nAmKcAz** [comment]
Note: I am also porting some of this fix into our engine startup code. Thank you for reporting

**Comment by RG-nAmKcAz** [comment]
@jmerle Version 1.4.0 of RGBot is now available.  This makes RGBot an EventEmitter and it seamlessly handles passing through mineflayer events for `.on/.off/.once` so you can just use `RGBot.on` without having to worry about `RGBot.mineflayer().on`.

I also ported your `inject_allowed` changes into our bot launching engine code, but I did not update the sample in this file.  Feel free to update to 1.4.0 at your leisure and make any updates to this PR that you still find necessary.

Thank You

**Comment by jmerle** [comment]
@RG-nAmKcAz I updated this PR to include the `inject_allowed` changes and removed all changes to do with the match info emitter (now that that's no longer required).

**Review by RG-nAmKcAz — APPROVED** [review]

**Pull request merged**
