### PR TITLE
Update method signature

### PR DESCRIPTION
**Pull request by vontell**

### CODE REVIEW

**Review by RG-nAmKcAz — CHANGES_REQUESTED** [review]
Needs a version update

**Comment by vontell** [comment]
> Needs a version update

@RG-nAmKcAz wasn't sure if you saw my note in Slack - I think that we will be making a few other updates over the next few days so I figured I would wait to increase the version number - thoughts?

**Comment by RG-nAmKcAz** [comment]
> > Needs a version update
> 
> @RG-nAmKcAz wasn't sure if you saw my note in Slack - I think that we will be making a few other updates over the next few days so I figured I would wait to increase the version number - thoughts?

I saw your slack note after commenting.  That said, this will still need a version update before merging.  If you want to merge/publish it now as a 0.0.X change vs wait for later with other things and become a 0.X.0 change.  Either is fine.

**Comment by vontell** [comment]
@RG-nAmKcAz updated version! But did not publish yet

**Review by RG-nAmKcAz — APPROVED** [review]

**Review by abeizer — APPROVED** [review]

**Pull request merged**
